### ISSUE TITLE
Being VAT registered is a non-trivial, irrevocable burden, and not required until revenue exceeds ~£80k

### ISSUE THREAD

**Issue by jpluscplusm** [tadast/switching-to-contracting-uk#1]
I think you should note both the above points in your VAT section.
I'd PR a suggestion myself, but it's late in the day ... :-)

**Comment by tadast** [comment]
However, it allows you to claim some money back. If your annual income is ~50k it's more than an extra grand of income a year on the flat rate scheme.

However, I haven't been VAT registered long enough so I don't understand what the burdens are. Could you please share your experiences?

**Comment by lewispb** [comment]
I work for a medium size business that cannot be VAT registered and claim VAT back and so if I was to be VAT registered it would increase my day rate to them. Something to consider at least.

**Comment by jpluscplusm** [comment]
Apologies for the lack of update. There are at least 2 issues I'm aware of, which might be worth highlighting in the VAT/flat-rate/etc section of the doc.

1) As @lewispb says, non-VAT-registered companies will have to pay your VAT charge out of their own pocket, which makes you seem more expensive despite you gaining nothing from it (modulo the flat-rate win).

2a) The ongoing/periodic VAT accounting/reporting/payment burden, whilst not major, can be non-trivial, especially if your company isn't using the flat rate scheme. (2b) What's more, once you're VAT registered, the _deregistration_ process is additional work and (I /believe/) requires certain thresholds not to be exceeded for a 12 month window looking backwards. [NB: I'm very possibly wrong on this last detail; do check!]

I used to think getting onto the flat rate scheme was a no-brainer even when one doesn't exceed the VAT threshold, but internalising the above details has genuinely made me put off registering until I actually have to.

**Comment by roybarber** [comment]
If you are working with larger agencies / business then they will more likely gross over £150k pre vat. Meaning they will 100% not be on the flat rate scheme, meaning they WILL be claiming your VAT back. This makes you no more expensive than a sole trader.

An Agency with 5x devs on 30k a year will need to earn £150k gross before they even think about turning the lights on, hiring an office or making a profit.

**Comment by es6Test** [comment]
flat rate VAT is like a bonus
