### ISSUE TITLE
formations factory

### ISSUE THREAD

**Issue by slifin** [tadast/switching-to-contracting-uk#10]
The guide currently recommends: 
getting the "London business address" add-on

So I'm making my way through the sign up process I'm currently on step 4 
I've been asked 3 times in 3 different ways whether I want the london business address or not 
each one has a difference price

one of them costs £30 (director address in london) 
one of them costs £49.00 + VAT / year (Registered office address (required))
one of them costs £99.00 + VAT / year (Business address (optional))

Can we update the guide to mention which addon this guide is recommending, how much is costs and which step in sign up that addon is related to? 

I've added a picture for clarity

![image](https://cloud.githubusercontent.com/assets/198857/13555254/654a6058-e3b3-11e5-8cc4-9ab570df4d97.png)

**Comment by tadast** [comment]
>  I'd recommend getting the "London business address" add-on. 

If you choose to use Crunch, they'll provide you with the "registered office" address with no extra cost.

Basically the aim here is to avoid making your residential address public  (e.g. [by the Companies Hous](https://beta.companieshouse.gov.uk/)) to prevent identity fraud. If you're not worried about that it's ok to skip the add-on.
