### ISSUE TITLE
Recruiting Agents' commission

### ISSUE THREAD

**Issue by FergusInLondon** [tadast/switching-to-contracting-uk#11]
I was a bit surprised to see the Recruiting Agents' commission push me over budget, and lose me a contract (_despite being offered it already!_) this week.

I may file a Pull Request about this underneath the section about Recruiting Agents' if no one minds?

**Comment by FergusInLondon** [comment]
Pull Request #12 should address this.

**Comment by tadast** [comment]
I'm sorry to hear about your bad experience. I've merged the PR now.
