### ISSUE TITLE
Change in flat rate VAT scheme

### ISSUE THREAD

**Issue by krisleech** [tadast/switching-to-contracting-uk#17]
> As a company providing software development services you'll be adding 20% VAT to your client invoices. HMRC will take 14.5% of your flat rate turnover. For example, if you charge your client £1000, you'll add 20% VAT, totalling £1200. This is your flat rate turnover. You'll need to pay £1200 * 14.5% = £174 to HMRC. That leaves you with an extra 2.6% (£26.00 in this case) of income.

I believe this has changed and IT companies can no longer go on the VAT scheme, because it is being used to make money.

http://www.bbc.co.uk/news/business-38084493

**Comment by tadast** [comment]
Hey @krisleech, I have not heard about this before and my accountant has not mentioned this either - thank you. Have you recently gone through setting up a company and were recommended not to use the flat VAT scheme?

**Comment by krisleech** [comment]
I've had a limited company over 10 years. De-registered for VAT recently. It would be worth asking your accountant, but I was under he impression you can't go on the flat VAT scheme anymore unless you fall in to a certain category of business. And you have to move off it if you are already on it if you don't met the criteria.

**Comment by caevv** [comment]
Interesting, I was just registered and my accountant got me into flat VAT.

**Comment by krisleech** [comment]
I might be mistaken, it has something to do with being classed as a "limited cost business". Maybe only the rate has changed.

This might be useful for finding out: https://www.tax.service.gov.uk/check-your-vat-flat-rate/vat-return-period

For me it says "Use the 16.5% VAT flat rate".
