### ISSUE TITLE
Wrong calculation for the flat rate VAT

### ISSUE THREAD

**Issue by tmcdos** [tadast/switching-to-contracting-uk#19]
In your example, the price for the customer is 10,000 and you add 20% VAT so it becomes 12,000 because 20% of 10,000 is 2,000. HMRC takes 16,5% instead of 20% - so it should be 16,5/20 of 2,000. And this makes 2000 * 16.5/20 = 1650 leaving you a lot more than 20 pounds.

**Comment by tadast** [comment]
Hey @tmcdos, I'm not sure `2000 * 16.5/20 ` is correct. I believe you pay VAT on the full amount, 12,000 in this example, so `12,000 * 16.5/100 = 1980` Leaving you with `2,000 - 1980 = £20`.

[This calculator](https://firstfreelance.com/assets/libs/FlatRateCalc/) seems to confirm it:

![image](https://user-images.githubusercontent.com/218239/34306632-1cccb4fa-e73c-11e7-8d21-e23c881a0f69.png)

I also had a glance at my recent accounts and I'm pretty sure it matches the formula in the article.

Feel free to re-open the issue if I'm still wrong on this one :)

**Comment by tmcdos** [comment]
You are right - I completely neglected the fact that the flat rate VAT is over the `inclusive amount` instead of the `standard amount`. So in fact you do not gain 3,5% as I initially though - you only gain 0.2%
