### ISSUE TITLE
What license can these words be used under?

### ISSUE THREAD

**Issue by jpluscplusm** [tadast/switching-to-contracting-uk#23]
I'd really like to expand on this topic (pushing more into the daily/monthly/annual cycle of running a Ltd) and these words would be really useful to adapt as part of that.

Could a license be added to the repo?

**Comment by tadast** [comment]
Thanks @jpluscplusm, I've added an Attribution-ShareAlike Creative Commons licence. Should allow you to re-use the contents for both commercial and non-commercial use, as long as you link back to the original.
