### ISSUE TITLE
VAT and advertised daily rates

### ISSUE THREAD

**Issue by mbixby** [tadast/switching-to-contracting-uk#26]
Recruitment agencies will try to include VAT in the daily rate. If they advertise e.g. 600pd contract they will want you to charge them 500 + 100pd VAT, not 600pd + 120pd. Huge difference.

In b2b the standard is to obviously advertise prices without VAT, this is just a sneaky practice.

If you must speak to recruiters, always present your daily rate as exclusive of VAT and later verify that this aligns with your contract.

If you accidentally end up in such contract, just don't register for VAT. Switch to a better contract before you hit the VAT ceiling.

**Comment by tadast** [comment]
Wow, this is absurd, the first time I hear this. Feel free to open a PR and add a sentence to the paragraph about working with recruiters :)
