### ISSUE TITLE
"Getting an accountant" section reads like an ad for Crunch

### ISSUE THREAD

**Issue by mbixby** [tadast/switching-to-contracting-uk#27]
This section should list all the available options and first of all how to find a good local accountant.

https://uk.trustpilot.com/review/crunch.co.uk they're not all that great. Their response rate is not great, their service is for bookkeeping, not accountancy.

**Comment by tadast** [comment]
Hi @mbixby, the purpose of this repo is to offer a simple-to-follow linear workflow to get up and running, as I clearly state in the intro. I'm not aiming to offer 10 different ways to do the same thing and offload the burden of choosing to the reader – so this is an opinionated piece of work. Crunch might not be the best option, but that's the only option I've tried and it works very well for me.
