### ISSUE TITLE
Business savings account with interest

### ISSUE THREAD

**Issue by Ricardo1980** [tadast/switching-to-contracting-uk#29]
Hello,

Does anyone know a good business savings account?
Right now I have two accounts in metro bank (connected to Crunch).
The normal one and the savings account.
The last one only gives me 0.30% in interest, which is crap (although better than 0)

What recommendations do you have?
Thanks a lot.

**Comment by Ricardo1980** [comment]
I found this 
https://redwoodbank.co.uk/savings/95-day-savings-account/

1.6% interest rate. 

Does anyone know Redwoodbank?

**Comment by tadast** [comment]
Hi, this is a great topic to research! I haven't heard about redwood bank, but it looks appealing, the two things you need to consider is:
- the 95 day notice period – I think this is long enough to be a problem. Why not pay yourself dividends as soon as you can and fill out your personal ISA to get interest?
- check if it's covered by FSCS

Other thoughts: 
- paying HMRC taxes as early as you can. They will pay interest on early payment, currently 0.5%, which is higher than your metro offer :)
- keep an eye on https://www.marcus.co.uk/uk/en, their personal saving account offer is quite appealing, if they roll out a similar business solution it might be worth considering

**Comment by Ricardo1980** [comment]
1. There is another option with 30 days notice period and the interested is similar, slightly lower. 

2. Yes, it is. 

3.  I don’t understand that. Any link? I am interested. 

4. Nope. I don’t use anything related with Goldman Sachs.

**Comment by tadast** [comment]
If you pay your tax early HMRC will apply a 'repayment' interest rate on the amount you've paid early until it's due https://www.gov.uk/government/publications/rates-and-allowances-hmrc-interest-rates-for-late-and-early-payments/rates-and-allowances-hmrc-interest-rates

**Comment by Ricardo1980** [comment]
How does that work? Do I have to claim it or is it automatic?
Imagine for example this year, that ends 5 April 2019, when do I have to pay my taxes to get that interest? and when is it considered late? Thanks a lot.

**Comment by tadast** [comment]
I think corporation tax is based on when you've established a company, so after a year passes you can calculate the corp tax and pay it immediately even though it's not due for another 9 months. You accountant should know all the deadlines so all you need to do is pay as soon as you know how much you owe, and HMRC will automatically refund it to your account (if that's set up - you have to call HMRC) or send you a check otherwise.
