### ISSUE TITLE
Some negative reviews of Crunch I found whilst researching.

### ISSUE THREAD

**Issue by Jakkc** [tadast/switching-to-contracting-uk#31]
A lot of helpful information in this document, but I found some rather concerning reviews after doing some due diligence on Crunch. Think this information should probably be available for anyone looking for an accounting service.

- People found it difficult to speak to an accountant
- After finally getting through people are told contradictory information and / or told to read articles on the Crunch website.
- Over time service has degraded and become not much more than automated emails.
- Reports of getting accounts wrong - are Crunch liable in this scenario?
- Accounts being filed late
- Client managers unwilling to take responsibility, try and wiggle and place blame on client.
- Unqualified staff 
- People reporting upto 3 weeks of silence before getting response to an important upcoming event
- Multiple reports of people closing account and still being charged 6 months later
- Somebody saying they had to take a bank loan out to cover extra tax payments they were burdened with after Crunch made accounting errors.

Most of these notes taken from [here](https://www.reviews.co.uk/company-reviews/store/crunch-accounting) and all within the last 12 months.

**Comment by tadast** [comment]
Hi, although I do not share the same experience, it is indeed concerning. However, I'm not sure what the alternatives are. I can't just recommend people to find a local accountant, as this does not make things easier at all. 

I am also not confident recommending another service without trying it myself.

Furthermore, suggesting multiple options would also defy the purpose of this document, as this is meant to be one simple (not necessarily the best one) way to set things up and focus on work rather than research for the admin side of things.

I guess I'll leave this issue open so that those willing to do more research can take it into account.

**Comment by willsheppard** [comment]
If you're looking for an accountant, I have had a good experience with Nixon Williams. Their Gold package costs £95 + vat (compared with Crunch's £71.50 + vat), but they have none of the problems mentioned here. I have an account manager who always answers my questions promptly. They file all the necessary limited company papers several times a year with HMRC, including my personal tax return.

Nixon Williams packages:

* [Vantage Gold](https://rb.gy/fu0khd) 
* [Vantage Platinum](https://rb.gy/orkgbx) 
* [Vantage Professional](https://rb.gy/knv5kr) 

The professional package also includes business insurance.

**Comment by tadast** [comment]
@willsheppard interesting, never heard of them, thanks. What software do they use, freeagent or something of their own?

**Comment by willsheppard** [comment]
Seems to be a custom solution.

Another killer feature is that if you sign up for a business bank account with Metro bank through them, they can integrate it with the accounting front-end in your control panel so it's always in sync.

I haven't tried it yet as I use a different bank.

**Comment by tadast** [comment]
Crunch, as of lately, have an integration with all banks via Open Banking APIs for accounting/reconciliation, so it's all in sync by default. 

Honestly, I'd be reluctant to switching, given my personal experience - I like their recently renewed software and haven't had any problems with the service recently (once everything is set up and running, I rarely need any human intervention). 

Out of curiosity, I was considering checking out Freeagent and seeing how difficult would it be to do everything myself, without an accountant, but I would not recommend that for people new to contracting.

My friends have also mentioned https://www.maslins.co.uk, that's an accounting service using FreeAgent. This (or similar) would probably be my second choice given FreeAgent's reputation. Would make further switching, if needed, easier than any custom platform.

**Comment by willsheppard** [comment]
Update: Nixon Williams got hacked years ago.

FreeAgent integration with Mettle Bank account is now the latest technology.
