### ISSUE TITLE
No mention of ICO registration

### ISSUE THREAD

**Issue by cisherlock** [tadast/switching-to-contracting-uk#34]
For most developers starting out it will be a requirement and annual charge of £40.

As a business owner it is important to understand the difference between controller and processor, and understand your obligations with regard to data privacy.

[ico.org.uk](https://ico.org.uk) - "Every organisation or sole trader who processes personal information needs to pay a data protection fee to the ICO, unless they are exempt"

The website contains a [short self assessment](https://ico.org.uk/for-organisations/data-protection-fee/)

**Comment by tadast** [comment]
From my understanding, regular contractors who do client work do not process any personal information (contracts are except as they're legal documents). I could perhaps mention that in the guide, but at the same time do not want to overload it as ICO tend to contact each business owner and they can then do the self assessment
