### ISSUE TITLE
Is it possible to work as a contractor as a sole trader

### ISSUE THREAD

**Issue by o-t-w** [tadast/switching-to-contracting-uk#36]
I have been told that at a lower salary it is beneficial to avoid the hassle of setting up a company and to instead work as a sole trader. Is this possible when contracting?

**Comment by przemub** [comment]
It technically is, but many businesses and agencies will want you to have a limited company - so it is quite uncommon. I worked this way before and it was indeed simpler in terms of paperwork, though it is still rather easy to set up a limited company.
