### ISSUE TITLE
Advice on when to start a limited company

### ISSUE THREAD

**Issue by phildotdev** [tadast/switching-to-contracting-uk#5]
Hi, Wanted to discuss before a PR.

I'm not convinced the 50k+ figure is the right way to describe when to form a Ltd. Company. In my experience, when working direct to clients and agencies they prefer a b2b/supplier contract which you wouldn't get with a sole trader. There is also some protections, to a point when going limited.

I'd like to change the wording to point to limited company straight away, if the person is serious about full time freelancing.

Happy to PR.

**Comment by NoelDavies** [comment]
I think the Ltd company route is great if you have the proper contracts in place (seek a lawyer for proper legal advice here), I've worked under an umbrella who've done it all for me, and I've also done it under my own steam. Both are great, but it depends what you're looking for.

**Comment by tadast** [comment]
The 50k is a arbitrary, I would be happy to replace it with something better. However, I wouldn't like to make it too complicated to the reader as digging into minutia of sole trading v.s. umbrella v.s. incorporating could raise more questions than answers.

I think if someone is aiming for 50k or higher is a good indicator a reader is committing to it fully and is ok to hire an accountant. Whereas is they are just planning to do some freelancing here and there they might be better off as a sole trader and use an umbrella company in case a client requires to deal with a company.

That's my reasoning. if you can make it clearer without using the £50k figure open up a PR :)

**Comment by roybarber** [comment]
Agree there is not figure really, its more about risk control. Although things like accountancy fees are higher, but then taxation is lower. I wouldn't be anything other than a LTD company on day 1 of freelancing.

**Comment by tbm** [comment]
You could replace the 50k figure with a list of considerations that may influence whether sole trader vs Ltd makes sense.

These could include:

* The supplier contract thing mentioned by OP
* Tax efficiency (depending on turnover Ltd might make sense in combination with dividend and small salary)
